"""empty message

Revision ID: 812eee9b33bb
Revises: 8552ddb963a4
Create Date: 2019-09-01 09:48:42.536621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '812eee9b33bb'
down_revision = '8552ddb963a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pic_filepath', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'pic_filepath')
    # ### end Alembic commands ###
