"""empty message

Revision ID: 837a1eb1c414
Revises: face972c539f
Create Date: 2019-08-24 10:37:50.967981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '837a1eb1c414'
down_revision = 'face972c539f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('title', sa.String(length=55), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'title')
    # ### end Alembic commands ###
