"""empty message

Revision ID: 8552ddb963a4
Revises: 1017f97a209c
Create Date: 2019-08-26 15:57:01.762496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8552ddb963a4'
down_revision = '1017f97a209c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('facebook', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('instagram', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('tagline', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('twitter', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'twitter')
    op.drop_column('user', 'tagline')
    op.drop_column('user', 'instagram')
    op.drop_column('user', 'facebook')
    # ### end Alembic commands ###
